// Generated browser runtime from src/main/kotlin/Drawer.kt.
const artifacts=[
 {id:"weather-letter",title:"Weather Letter",type:"CORRESPONDENCE / CLIMATE",image:"assets/weather-letter.webp",description:"A letter whose contents refused to remain figurative. It rains upward when somebody nearby is avoiding a reply.",action:"BREAK THE WAX SEAL",observation:"The storm recognizes your name and immediately becomes more specific.",color:"#55758d"},
 {id:"staircase-key",title:"Staircase Key",type:"ACCESS / VERTICAL",image:"assets/staircase-key.webp",description:"A key for a lock located several floors inside itself. Every step is smaller than the last, but the landing never gets closer.",action:"CLIMB THREE STEPS",observation:"You arrive one inch above where you started, carrying a memory of red carpet.",color:"#7c432f"},
 {id:"moon-teacup",title:"Moon in a Teacup",type:"REFRESHMENTS / NIGHT",image:"assets/moon-teacup.webp",description:"The night shift has been steeping since 11:42 p.m. The stars are decorative, but the moon appears fully caffeinated.",action:"TAKE ONE SIP",observation:"For a moment, every shadow in the room points toward tomorrow.",color:"#27365c"},
 {id:"forest-file",title:"The Green File",type:"RECORDS / OVERGROWN",image:"assets/forest-file.webp",description:"Filed under administrative growth. Each tab opens onto a different path; none lead back to the cabinet where it was found.",action:"FOLLOW THE SMALLEST PATH",observation:"A mushroom stamps your paperwork APPROVED and refuses to elaborate.",color:"#58412e"},
 {id:"koi-drawer",title:"Aquatic Drawer",type:"FURNITURE / TIDAL",image:"assets/koi-drawer.webp",description:"Its waterline remains level even when the drawer is tilted. The koi is believed to be responsible for all missing paper clips.",action:"ASK THE KOI WHAT IT SAW",observation:"The koi circles twice, which is either testimony or excellent legal advice.",color:"#315b65"},
 {id:"paper-door",title:"Door of Pending Matters",type:"EXIT / UNCONFIRMED",image:"assets/paper-door.webp",description:"Bound from documents that were never quite finished. The stair beyond it rises through every margin somebody left blank.",action:"KNOCK ON THE MARGIN",observation:"A smaller version of your knock answers from three pages ahead.",color:"#8a5135"}
];
let index=0,seen=new Set(),activated=new Set(),soundOn=true,dragStart=null,dragOffset=0,audio=null,entered=false;
const q=s=>document.querySelector(s),rail=q("#rail"),cabinet=q("#cabinet"),landing=q("#landing"),record=q("#record");
function tone(f=220,d=.12,t="sine"){if(!soundOn)return;try{const AudioCtor=window.AudioContext||window.webkitAudioContext;if(!AudioCtor)return;audio=audio||new AudioCtor();if(audio.state==="suspended")audio.resume?.();const o=audio.createOscillator(),g=audio.createGain();o.type=t;o.frequency.value=f;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(_){/* Sound must never block the drawer. */}}
function build(){rail.innerHTML=artifacts.map((a,i)=>`<button class="artifact" data-index="${i}" type="button" aria-label="Open ${a.title}"><img src="${a.image}" alt=""><span class="artifact-meta"><span>OBJECT ${String(i+1).padStart(2,"0")}<h3>${a.title}</h3></span><b>↗</b></span></button>`).join("");rail.querySelectorAll(".artifact").forEach(x=>x.addEventListener("click",()=>openRecord(+x.dataset.index)))}
function announce(message){let toast=q("#drawerToast");if(!toast){toast=document.createElement("div");toast.id="drawerToast";toast.className="toast";toast.setAttribute("role","status");document.body.append(toast)}toast.textContent=message;toast.classList.remove("show");requestAnimationFrame(()=>toast.classList.add("show"));clearTimeout(announce.timer);announce.timer=setTimeout(()=>toast.classList.remove("show"),1800)}
function enter(){if(entered)return;entered=true;tone(100,.6,"triangle");landing.classList.add("leaving");announce("The drawer is opening…");setTimeout(()=>{landing.style.display="none";cabinet.classList.add("visible");cabinet.setAttribute("aria-hidden","false");select(0);cabinet.scrollIntoView({block:"start"})},520)}
function select(n){index=(n+artifacts.length)%artifacts.length;const cardWidth=Math.min(innerWidth*.46,570)+28;rail.style.transform=`translateX(${-index*cardWidth}px)`;rail.querySelectorAll(".artifact").forEach((card,i)=>card.classList.toggle("current",i===index));q("#progress").style.width=`${((index+1)/artifacts.length)*100}%`;q("#count").textContent=`${String(seen.size).padStart(2,"0")} / 06`;q("#depth").textContent=index<2?"SHALLOW INTERIOR":index<4?"BELOW WEATHER":"UNLICENSED DEPTH";tone(150+index*28,.06,"triangle")}
function openRecord(n){index=n;const a=artifacts[n];seen.add(a.id);const image=q("#recordImage");image.className="";image.src=a.image;image.alt=a.title;record.dataset.artifact=a.id;q("#recordNumber").textContent=`OBJECT ${String(n+1).padStart(2,"0")} / 06`;q("#recordType").textContent=a.type;q("#recordTitle").textContent=a.title;q("#recordDescription").textContent=a.description;const b=q("#activate");b.disabled=false;b.classList.remove("confirmed");record.classList.add("open");record.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";q(".record-visual").style.background=`radial-gradient(circle,${a.color},#171426 70%)`;q("#count").textContent=`${String(seen.size).padStart(2,"0")} / 06`;renderGame();announce(`${a.title} is ready to investigate`);tone(280+n*24,.16,"triangle")}
function activate(){const a=artifacts[index],image=q("#recordImage"),button=q("#activate");activated.add(a.id);q("#observation").textContent=a.observation;image.className=`reacting ${a.id}`;record.classList.add("reaction-live");button.textContent="REACTION RECORDED ✓";button.classList.add("confirmed");announce(a.observation);tone(440,.5,"sine");setTimeout(()=>{image.className="";record.classList.remove("reaction-live");button.textContent="REPLAY THE REACTION";button.classList.remove("confirmed")},2300);if(activated.size===artifacts.length){q("#bottomMessage").textContent="All six objects have testified. The paper door has stopped pretending to be locked.";q("#openDoor").disabled=false;q("#openDoor").classList.add("unlocked")}}
function closeRecord(){q("#recordImage").className="";record.classList.remove("open","reaction-live");record.setAttribute("aria-hidden","true");document.body.style.overflow="";select(index);if(seen.size===artifacts.length){q("#bottom").classList.add("visible");q("#bottom").setAttribute("aria-hidden","false");setTimeout(()=>q("#bottom").scrollIntoView({behavior:"smooth"}),300)}}
function openEnding(){q("#ending").classList.add("visible");q("#ending").setAttribute("aria-hidden","false");document.body.style.overflow="hidden";tone(70,1.6,"sine")}
const gameState={};
function gameComplete(message){const a=artifacts[index];activated.add(a.id);q("#observation").textContent=`COMPLETE — ${message} ${a.observation}`;q("#gameZone")?.classList.add("solved");announce("Artifact solved ✓");tone(440,.5,"sine");if(activated.size===artifacts.length){q("#bottomMessage").textContent="All six objects have testified. The paper door has stopped pretending to be locked.";q("#openDoor").disabled=false;q("#openDoor").classList.add("unlocked")}}
function gameShell(instruction,html){let zone=q("#gameZone");if(!zone){zone=document.createElement("div");zone.id="gameZone";zone.className="game-zone";q(".record-copy").insertBefore(zone,q("#observation"))}zone.className="game-zone";zone.innerHTML=`<p class="game-instruction">${instruction}</p>${html}`;q("#activate").hidden=true;return zone}
function renderGame(){const a=artifacts[index];q("#observation").textContent=activated.has(a.id)?"Solved before. You can play it again.":"Complete the field test to record an observation.";if(a.id==="weather-letter")weatherGame();if(a.id==="staircase-key")keyGame();if(a.id==="moon-teacup")moonGame();if(a.id==="forest-file")forestGame();if(a.id==="koi-drawer")koiGame();if(a.id==="paper-door")doorGame()}
function weatherGame(){const words=["THE","RAIN","IS","FALLING","UPWARD"],shuffled=["UPWARD","THE","FALLING","RAIN","IS"];let chosen=[];const zone=gameShell("Reassemble the sentence before the ink washes away.",`<div class="word-bank">${shuffled.map(w=>`<button type="button" data-word="${w}">${w}</button>`).join("")}</div><div class="answer-line" aria-live="polite">Choose the first word…</div><button class="game-reset" type="button">RESET</button>`);zone.querySelectorAll("[data-word]").forEach(b=>b.onclick=()=>{chosen.push(b.dataset.word);b.disabled=true;zone.querySelector(".answer-line").textContent=chosen.join(" ");if(chosen.length===5){chosen.join(" ")===words.join(" ")?gameComplete("The letter now reads clearly."):(announce("The sentence slipped apart—try again"),setTimeout(weatherGame,650))}});zone.querySelector(".game-reset").onclick=weatherGame}
function keyGame(){let step=0;const path=["UP","RIGHT","UP","LEFT","UP"];const zone=gameShell("Climb the staircase hidden inside the key. One wrong turn returns you to the landing.",`<div class="stair-map"><b>LANDING</b><span id="stairProgress">· · · · ·</span><b>LOCK</b></div><div class="direction-pad"><button data-dir="UP">↑</button><button data-dir="LEFT">←</button><button data-dir="RIGHT">→</button><button data-dir="DOWN">↓</button></div>`);zone.querySelectorAll("[data-dir]").forEach(b=>b.onclick=()=>{if(b.dataset.dir===path[step]){step++;q("#stairProgress").textContent=path.map((_,i)=>i<step?"◆":"·").join(" ");tone(220+step*40,.08);if(step===path.length)gameComplete("You reached the lock without changing floors.")}else{step=0;q("#stairProgress").textContent="· · · · ·";announce("Back to the landing")}})}
function moonGame(){let value=0,running=false,timer;const zone=gameShell("Hold the cup beneath the moon. Release it inside the silver band.",`<div class="steep-track"><i></i><span></span></div><button class="hold-moon" type="button">PRESS & HOLD TO STEEP</button>`),bar=zone.querySelector(".steep-track i"),button=zone.querySelector(".hold-moon");const start=()=>{if(running)return;running=true;timer=setInterval(()=>{value=(value+1)%101;bar.style.width=value+"%"},18)};const stop=()=>{if(!running)return;running=false;clearInterval(timer);if(value>=62&&value<=76)gameComplete("The moon is perfectly steeped.");else announce(value<62?"Too pale—steep it longer":"Too dark—the night overflowed")};button.onpointerdown=start;button.onpointerup=stop;button.onpointerleave=stop}
function forestGame(){let node="start";const paths={start:["moss","fern"],moss:["mushroom","river"],fern:["thorns","mushroom"]};const zone=gameShell("Follow the smallest path. The forest remembers impatient choices.",`<div class="path-story">A folder opens into two narrow paths.</div><div class="path-options"></div>`);function show(){const opts=paths[node];if(!opts){node==="mushroom"?gameComplete("The mushroom clerk stamped your file."):(announce("The path folded shut"),node="start",setTimeout(show,500));return}zone.querySelector(".path-story").textContent=node==="start"?"A folder opens into two narrow paths.":`The ${node} path divides again.`;zone.querySelector(".path-options").innerHTML=opts.map(x=>`<button data-path="${x}">${x.toUpperCase()}</button>`).join("");zone.querySelectorAll("[data-path]").forEach(b=>b.onclick=()=>{node=b.dataset.path;show()})}show()}
function koiGame(){let caught=0;const zone=gameShell("The koi stole three paper clips. Catch each one as it surfaces.",`<div class="pond-game"><button class="paperclip" aria-label="Catch paper clip">⌇</button><span>RECOVERED <b>0</b> / 3</span></div>`),clip=zone.querySelector(".paperclip"),pond=zone.querySelector(".pond-game");function move(){clip.style.left=(8+Math.random()*78)+"%";clip.style.top=(8+Math.random()*60)+"%"}clip.onclick=()=>{caught++;pond.querySelector("b").textContent=caught;tone(320+caught*80,.1);if(caught===3){clip.remove();gameComplete("All paper clips were recovered. The koi denies involvement.")}else move()};move()}
function doorGame(){let taps=[],start=0;const target=[0,260,520,1040];const zone=gameShell("Knock this rhythm: quick, quick, pause, knock.",`<div class="rhythm-display"><span>● ●</span><i></i><span>●</span></div><button class="knock-button" type="button">KNOCK</button><button class="game-reset" type="button">CLEAR</button>`);zone.querySelector(".knock-button").onclick=()=>{const now=performance.now();if(!start)start=now;taps.push(now-start);zone.querySelector(".knock-button").textContent=`KNOCK ${taps.length}/4`;tone(90,.12,"square");if(taps.length===4){const ok=Math.abs((taps[1]-taps[0])-260)<180&&Math.abs((taps[2]-taps[1])-260)<180&&(taps[3]-taps[2])>350;if(ok)gameComplete("Something knocked back from the next page.");else{announce("That was not the door’s rhythm");setTimeout(doorGame,600)}}};zone.querySelector(".game-reset").onclick=doorGame}
function startDrag(e){dragStart=e.clientX;dragOffset=index}function moveDrag(e){if(dragStart===null)return;const delta=e.clientX-dragStart;rail.style.transform=`translateX(${-(dragOffset*(Math.min(innerWidth*.46,570)+28))+delta}px)`}function endDrag(e){if(dragStart===null)return;const delta=e.clientX-dragStart;if(Math.abs(delta)>70)select(dragOffset+(delta<0?1:-1));else select(dragOffset);dragStart=null}
q("#enter").onclick=enter;q("#heroObject").onclick=enter;q("#previous").onclick=()=>select(index-1);q("#next").onclick=()=>select(index+1);q("#recordClose").onclick=closeRecord;q("#activate").onclick=activate;q("#openDoor").onclick=openEnding;q("#again").onclick=()=>location.reload();q("#sound").onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=`SOUND / ${soundOn?"ON":"OFF"}`;e.currentTarget.setAttribute("aria-pressed",soundOn);if(soundOn)tone(300,.1)};q(".rail-shell").addEventListener("pointerdown",startDrag);addEventListener("pointermove",moveDrag);addEventListener("pointerup",endDrag);addEventListener("keydown",e=>{if(record.classList.contains("open")&&e.key==="Escape")closeRecord();else if(cabinet.classList.contains("visible")&&e.key==="ArrowRight")select(index+1);else if(cabinet.classList.contains("visible")&&e.key==="ArrowLeft")select(index-1)});addEventListener("pointermove",e=>{document.documentElement.style.setProperty("--mx",`${e.clientX/innerWidth*100}%`);document.documentElement.style.setProperty("--my",`${e.clientY/innerHeight*100}%`)});document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;b.classList.add("button-hit");setTimeout(()=>b.classList.remove("button-hit"),220)});build();
