// Generated browser runtime from src/main/kotlin/Drawer.kt.
const artifacts=[
 {id:"weather-letter",title:"Weather Letter",type:"CORRESPONDENCE / CLIMATE",image:"assets/weather-letter.webp",description:"A letter whose contents refused to remain figurative. It rains upward when somebody nearby is avoiding a reply.",action:"BREAK THE WAX SEAL",observation:"The storm recognizes your name and immediately becomes more specific.",color:"#55758d"},
 {id:"staircase-key",title:"Staircase Key",type:"ACCESS / VERTICAL",image:"assets/staircase-key.webp",description:"A key for a lock located several floors inside itself. Every step is smaller than the last, but the landing never gets closer.",action:"CLIMB THREE STEPS",observation:"You arrive one inch above where you started, carrying a memory of red carpet.",color:"#7c432f"},
 {id:"moon-teacup",title:"Moon in a Teacup",type:"REFRESHMENTS / NIGHT",image:"assets/moon-teacup.webp",description:"The night shift has been steeping since 11:42 p.m. The stars are decorative, but the moon appears fully caffeinated.",action:"TAKE ONE SIP",observation:"For a moment, every shadow in the room points toward tomorrow.",color:"#27365c"},
 {id:"forest-file",title:"The Green File",type:"RECORDS / OVERGROWN",image:"assets/forest-file.webp",description:"Filed under administrative growth. Each tab opens onto a different path; none lead back to the cabinet where it was found.",action:"FOLLOW THE SMALLEST PATH",observation:"A mushroom stamps your paperwork APPROVED and refuses to elaborate.",color:"#58412e"},
 {id:"koi-drawer",title:"Aquatic Drawer",type:"FURNITURE / TIDAL",image:"assets/koi-drawer.webp",description:"Its waterline remains level even when the drawer is tilted. The koi is believed to be responsible for all missing paper clips.",action:"ASK THE KOI WHAT IT SAW",observation:"The koi circles twice, which is either testimony or excellent legal advice.",color:"#315b65"},
 {id:"paper-door",title:"Door of Pending Matters",type:"EXIT / UNCONFIRMED",image:"assets/paper-door.webp",description:"Bound from documents that were never quite finished. The stair beyond it rises through every margin somebody left blank.",action:"KNOCK ON THE MARGIN",observation:"A smaller version of your knock answers from three pages ahead.",color:"#8a5135"}
];
let index=0,seen=new Set(),activated=new Set(),soundOn=true,dragStart=null,dragOffset=0,audio=null;
const q=s=>document.querySelector(s),rail=q("#rail"),cabinet=q("#cabinet"),landing=q("#landing"),record=q("#record");
function tone(f=220,d=.12,t="sine"){if(!soundOn)return;audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=t;o.frequency.value=f;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function build(){rail.innerHTML=artifacts.map((a,i)=>`<button class="artifact" data-index="${i}" type="button" aria-label="Open ${a.title}"><img src="${a.image}" alt=""><span class="artifact-meta"><span>OBJECT ${String(i+1).padStart(2,"0")}<h3>${a.title}</h3></span><b>↗</b></span></button>`).join("");rail.querySelectorAll(".artifact").forEach(x=>x.addEventListener("click",()=>openRecord(+x.dataset.index)))}
function enter(){tone(100,.6,"triangle");landing.animate([{opacity:1},{opacity:0,transform:"scale(.97)"}],{duration:600,fill:"forwards"});setTimeout(()=>{landing.style.display="none";cabinet.classList.add("visible");cabinet.setAttribute("aria-hidden","false");select(0)},580)}
function select(n){index=(n+artifacts.length)%artifacts.length;const cardWidth=Math.min(innerWidth*.46,570)+28;rail.style.transform=`translateX(${-index*cardWidth}px)`;q("#progress").style.width=`${((index+1)/artifacts.length)*100}%`;q("#count").textContent=`${String(seen.size).padStart(2,"0")} / 06`;q("#depth").textContent=index<2?"SHALLOW INTERIOR":index<4?"BELOW WEATHER":"UNLICENSED DEPTH";tone(150+index*28,.06,"triangle")}
function openRecord(n){index=n;const a=artifacts[n];seen.add(a.id);q("#recordImage").src=a.image;q("#recordImage").alt=a.title;q("#recordNumber").textContent=`OBJECT ${String(n+1).padStart(2,"0")} / 06`;q("#recordType").textContent=a.type;q("#recordTitle").textContent=a.title;q("#recordDescription").textContent=a.description;q("#observation").textContent=activated.has(a.id)?a.observation:"Observation pending.";const b=q("#activate");b.textContent=activated.has(a.id)?"OBSERVATION RECORDED":a.action;b.disabled=activated.has(a.id);record.classList.add("open");record.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";q(".record-visual").style.background=`radial-gradient(circle,${a.color},#171426 70%)`;q("#count").textContent=`${String(seen.size).padStart(2,"0")} / 06`;tone(280+n*24,.16,"triangle")}
function activate(){const a=artifacts[index];activated.add(a.id);q("#observation").textContent=a.observation;q("#activate").textContent="OBSERVATION RECORDED";q("#activate").disabled=true;tone(440,.5,"sine");if(activated.size===artifacts.length){q("#bottomMessage").textContent="All six objects have testified. The paper door has stopped pretending to be locked.";q("#openDoor").disabled=false}}
function closeRecord(){record.classList.remove("open");record.setAttribute("aria-hidden","true");document.body.style.overflow="";select(index);if(seen.size===artifacts.length){q("#bottom").classList.add("visible");q("#bottom").setAttribute("aria-hidden","false");setTimeout(()=>q("#bottom").scrollIntoView({behavior:"smooth"}),300)}}
function openEnding(){q("#ending").classList.add("visible");q("#ending").setAttribute("aria-hidden","false");document.body.style.overflow="hidden";tone(70,1.6,"sine")}
function startDrag(e){dragStart=e.clientX;dragOffset=index}function moveDrag(e){if(dragStart===null)return;const delta=e.clientX-dragStart;rail.style.transform=`translateX(${-(dragOffset*(Math.min(innerWidth*.46,570)+28))+delta}px)`}function endDrag(e){if(dragStart===null)return;const delta=e.clientX-dragStart;if(Math.abs(delta)>70)select(dragOffset+(delta<0?1:-1));else select(dragOffset);dragStart=null}
q("#enter").onclick=enter;q("#heroObject").onclick=enter;q("#previous").onclick=()=>select(index-1);q("#next").onclick=()=>select(index+1);q("#recordClose").onclick=closeRecord;q("#activate").onclick=activate;q("#openDoor").onclick=openEnding;q("#again").onclick=()=>location.reload();q("#sound").onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=`SOUND / ${soundOn?"ON":"OFF"}`;e.currentTarget.setAttribute("aria-pressed",soundOn);if(soundOn)tone(300,.1)};q(".rail-shell").addEventListener("pointerdown",startDrag);addEventListener("pointermove",moveDrag);addEventListener("pointerup",endDrag);addEventListener("keydown",e=>{if(record.classList.contains("open")&&e.key==="Escape")closeRecord();else if(cabinet.classList.contains("visible")&&e.key==="ArrowRight")select(index+1);else if(cabinet.classList.contains("visible")&&e.key==="ArrowLeft")select(index-1)});addEventListener("pointermove",e=>{document.documentElement.style.setProperty("--mx",`${e.clientX/innerWidth*100}%`);document.documentElement.style.setProperty("--my",`${e.clientY/innerHeight*100}%`)});build();
